### ISSUE TITLE
Combining jinja2 method with CSV learner data

### ISSUE THREAD

**Issue by ndporter** [carpentries/learner-certificates#5]
Can you clarify whether (and how) to it's possible to use csv input to create multiple learner certificates from a CSV file from the command line? I can get a single certificate with:
`jinja2 swc-attendance.svg -D name="Learner Name" -D date="August 9, 2022" -D instructor="Instructor Name" > test.svg`

...but that requires specifying each learner individually. I've been unable to successful use the python script directly with cairo2.

If I have a csv specified per line 32 in `certificates.py` is there a way to adapt the command line input above to use that CSV? Thanks.

**Comment by maneesha** [comment]
@ndporter  Can you share the errors you're getting with using `cairo2`?

Also, we can also generate learner attendance certificates and email them directly to the attendees.  Please send us an email at workshops@carpentries.org for more information.

**Comment by ndporter** [comment]
Thanks @maneesha . Since we self-host, I figure it's easiest to DIY.  Here's the call and the error I get. I have installed cairosvg with pip and cairo with port (on my Mac OSX Monterey):
`(base) ndporter@NDPORTER431816 learner-certificates % python bin/certificates.py -c input.csv
Traceback (most recent call last):
  File "/Users/ndporter/learner-certificates/bin/certificates.py", line 56, in <module>
    import cairosvg
  File "/Users/ndporter/opt/anaconda3/lib/python3.9/site-packages/cairosvg/__init__.py", line 26, in <module>
    from . import surface  # noqa isort:skip
  File "/Users/ndporter/opt/anaconda3/lib/python3.9/site-packages/cairosvg/surface.py", line 9, in <module>
    import cairocffi as cairo
  File "/Users/ndporter/opt/anaconda3/lib/python3.9/site-packages/cairocffi/__init__.py", line 48, in <module>
    cairo = dlopen(
  File "/Users/ndporter/opt/anaconda3/lib/python3.9/site-packages/cairocffi/__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': dlopen(libcairo.so.2, 0x0002): tried: '/Users/ndporter/opt/anaconda3/lib/libcairo.so.2' (no such file), '/Users/ndporter/opt/anaconda3/lib/libcairo.so.2' (no such file), '/Users/ndporter/opt/anaconda3/lib/python3.9/site-packages/../../libcairo.so.2' (no such file), '/Users/ndporter/opt/anaconda3/lib/libcairo.so.2' (no such file), '/Users/ndporter/opt/anaconda3/bin/../lib/libcairo.so.2' (no such file), 'libcairo.so.2' (no such file), '/usr/local/lib/libcairo.so.2' (no such file), '/usr/lib/libcairo.so.2' (no such file), '/Users/ndporter/learner-certificates/libcairo.so.2' (no such file)
cannot load library 'libcairo.2.dylib': dlopen(libcairo.2.dylib, 0x0002): tried: '/Users/ndporter/opt/anaconda3/lib/libcairo.2.dylib' (no such file), '/Users/ndporter/opt/anaconda3/lib/libcairo.2.dylib' (no such file), '/Users/ndporter/opt/anaconda3/lib/python3.9/site-packages/../../libcairo.2.dylib' (no such file), '/Users/ndporter/opt/anaconda3/lib/libcairo.2.dylib' (no such file), '/Users/ndporter/opt/anaconda3/bin/../lib/libcairo.2.dylib' (no such file), 'libcairo.2.dylib' (no such file), '/usr/local/lib/libcairo.2.dylib' (no such file), '/usr/lib/libcairo.2.dylib' (no such file), '/Users/ndporter/learner-certificates/libcairo.2.dylib' (no such file)
cannot load library 'libcairo-2.dll': dlopen(libcairo-2.dll, 0x0002): tried: '/Users/ndporter/opt/anaconda3/lib/libcairo-2.dll' (no such file), '/Users/ndporter/opt/anaconda3/lib/libcairo-2.dll' (no such file), '/Users/ndporter/opt/anaconda3/lib/python3.9/site-packages/../../libcairo-2.dll' (no such file), '/Users/ndporter/opt/anaconda3/lib/libcairo-2.dll' (no such file), '/Users/ndporter/opt/anaconda3/bin/../lib/libcairo-2.dll' (no such file), 'libcairo-2.dll' (no such file), '/usr/local/lib/libcairo-2.dll' (no such file), '/usr/lib/libcairo-2.dll' (no such file), '/Users/ndporter/learner-certificates/libcairo-2.dll' (no such file)`

**Comment by maneesha** [comment]
@ndporter  can you try uninstalling and reinstalling `cairosvg` and `cairo`? 

See note:

```
* Requires the python package 'cairosvg' to be installed.
  Please visit http://cairosvg.org/ for install instructions.
* Some systems may also need to have 'cairo' installed.
  Please visit http://cairographics.org/download/ for the same.
```

**Comment by maneesha** [comment]
(As a side note - when troubleshooting this error I also found another which I think is unrelated.  That one is fixed with #7)
